feat: HW11 is completed
XanderKon/hw-otus pull request #11
Opened 2023-11-07 20:06 UTC by XanderKon

## Домашнее задание №11 «Клиент TELNET»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2023-11-07 20:09 UTC, XanderKon commented on hw11_telnet_client/telnet.go
> +		fmt.Println(scanner.Text())
Вот этот момент выглядит как костыль, но я не могу понять как избавиться от него. Если это вынести в main.go, то там тогда проблема откуда брать этот текст.

2023-11-07 20:10 UTC, XanderKon commented on hw11_telnet_client/telnet_test.go
> +	t.Run("with error", func(t *testing.T) {
Не могу придумать более интересный тест. Хорошо бы проверить ошибки отправки и чтения, но не понятно, как их эмулировать.

2023-11-07 20:12 UTC, XanderKon commented on hw11_telnet_client/main.go
> +		if err != nil {
Здесь, как я понимаю, надо обратиться к той самой ссылке из подсказки: https://stackoverflow.com/questions/51317968/write-on-a-closed-net-conn-but-returned-nil-error

Перечитывал несколько раз, так и не понел, как решить :-(

2023-11-08 21:49 UTC, ityulkanov requested changes

2023-11-08 21:49 UTC, ityulkanov commented on hw11_telnet_client/main.go
> +		if err != nil {
C EOF у всех проблемы, похоже что наиболее близкое решение это `ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT, os.Interrupt)` а с eof только костыли крутить и специально как то перехватывать. Но я уже и не помню у кого это видел сейчас. Если не напишете, ничего страшного, думаю)

2023-11-08 21:49 UTC, ityulkanov commented on hw11_telnet_client/telnet.go
> +		fmt.Println(scanner.Text())
что send что receive могут просто использовать `io.Copy(client.conn, client.in)`

2023-11-08 21:49 UTC, ityulkanov commented on hw11_telnet_client/telnet_test.go
> +	t.Run("with error", func(t *testing.T) {
Я видел люди писали сложную логику с созданием горутин и эмуляций ввода вывода, но я бы такой подход не рекомендовал, всё же тесты не должны быть сложными для понимания, и уж тем более в них не должно быть таких конструкций как горутины. В общем рекомендую сосредоточиться на тесте send receive и прочих простых методов, не требующих создания интеграционных тестов

2023-11-09 16:26 UTC, XanderKon commented on hw11_telnet_client/telnet.go
> +		fmt.Println(scanner.Text())
Ага спасибо! Попадалось такое, но я почему-то подумал, что это какое-то читерство и не стал использовать. Вернул io.Copy.

2023-11-09 16:27 UTC, XanderKon commented on hw11_telnet_client/telnet_test.go
> +	t.Run("with error", func(t *testing.T) {
Добавил несколько тестов, но они прям что называется "из пальца"...

2023-11-09 16:30 UTC, XanderKon commented on hw11_telnet_client/main.go
> +		if err != nil {
Ну, что-то подобное я и использовал, только без SIGTERM, а то там тогда тесты в test.sh начинают триггеририться, там же процессы через kill -9 убиваются.

`ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGQUIT, syscall.SIGINT)`

CTRL+C ловится в этом случае нормально, а вот с CTRL+D (как указано в задаче) сделать так не удаётся. Думал, что придёт SIGQUIT, но не приходит, а просто убивает STDIN, как я понимаю.

2023-11-10 09:40 UTC, ityulkanov approved these changes

2023-11-25 19:09 UTC, merged